"""Refatoração completa do sistema de autenticação e créditos

Revision ID: 7679fde5796d
Revises: 001_phone_auth_referral_system
Create Date: 2025-09-02 16:10:56.108394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7679fde5796d'
down_revision: Union[str, None] = '001_phone_auth_referral_system'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
